travis:
  secure:
    BINSTAR_TOKEN: eGAXAvBmzjbAZ8zPz9i2rjbhGuNRPe9WHOZcRZo1TUzLC/FPstuKQIJQEfrQwjTwe+ZXRmdOMcyHYfjAI2dF6aiyoOi7HSL52EuAKZyiIen4Fa5Snkzzr+mkiq6MgCFyleSg4RAqeR/UM8WCDqSX5gzH9vEcHx+bodWXOXMxlLK/sQ7RvWJ+koq+JBLydvqwwUfy0uFTcMRdIx4fpdaNvlzPMXj6pLxoC7Eheh70XBcgcbR3SUr0OdKHVGepOYz7z+fdjhdntZzNPh4j8EQtzwnV6sR4xNNRYOGZtiQ6eE6Zl/Gw++tJfR6WgvChvRm9CEBR0RRUdX2Rb2XKN9wpc8+PdYBe+nY75n8/BKR4gvBjvBLQ4JkO3oB2Ykf4s1GC07F356oodDig2CaT/6QrIf2uM/ORy9cOa5FcLUFkNrZuFhTsvEIK4Pw5R42nuQzaHBP/Dlx9rT6hkcLDJhAP9hC6jaoemuC+A9Bz58w+8pxcR5bTyjve24/6nSpbbFuf9uWlc4tCA8Pd+E12FyI+mjUJtMxMcsw0fW35iEKLsoOVgqBQInixN+8+MxYZdfdL1hAsfEe91ntdwKFbZE3SG2b0LFyGdYHbzWyzZA9aNhZ8MVFqKF8qDjNPVSsdndv7aJFxtfxjAT9dEZOFFzYQqPGOGfALjOKwLNVwMgLbDog=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
